name: clang
    
on: 
  push:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: build test clang

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        sudo apt update
        sudo apt install mm-common clang-9 --yes
    - name: make clang-9
      run:  make CXX=clang-9
