name: g++
    
on: 
  push:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: build test g++

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        sudo apt update
        sudo apt install mm-common g++-8 --yes
    - name: make g++8
      run:  make CXX=g++-8
